name: Deploy Cloudflare Worker

on:
    workflow_run:
        workflows: ['CI']
        types:
            - completed
        branches: [main]

jobs:
    verify-ci:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - run: echo "CI passed, proceeding with deployment"
    deploy:
        needs: [verify-ci]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: npm

            - run: npm ci

            - uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: 'd5850c60070688eba8d6b5e7f3893f46'
                  secrets: DISCORD_WEBHOOK_URL
                  command: deploy
              env:
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
